### ISSUE TITLE
check-chef-nodes fails to run: uninitialized constant Chef::REST

### ISSUE THREAD

**Issue by z-matth** [sensu-plugins/sensu-plugins-chef#16]
Chef server and Sensu server have both been working in prod for a few months. Tried this chef plugin today and got error below

EX CMD:
`sudo /opt/sensu/embedded/bin/ruby ./check-chef-nodes.rb -U https://<MY_HOSNAME>/organizations/<ORG> -K /etc/chef/<MY_VALIDATOR>.pem`

ERROR:

> Check failed to run: uninitialized constant Chef::REST, ["./check-chef-nodes.rb:99:in `chef_api_connection'", "./check-chef-nodes.rb:69:in`connection'", "./check-chef-nodes.rb:73:in `nodes_last_seen'", "./check-chef-nodes.rb:103:in`any_node_stuck?'", "./check-chef-nodes.rb:86:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in`block in class:CLI'"]

check-chef-server.rb plugin script seems to work fine, however.

**Comment by cwjohnston** [comment]
@z-matth thanks for reporting this issue. I believe it is the case that `Chef::REST` was deprecated sometime circa Chef ~> 12.7, so I'm guessing that you are encountering this error because you are using a newer version of Chef than this plugin is compatible with. Until we can fix this in a future release, you see if the plugin works with Chef <= 12.6.

Will you please try using Chef gem <= 12.6 in the Ruby environment where your checks are running and see if it makes a difference?

**Comment by cwjohnston** [comment]
We pin Chef to 11.18.12 here: https://github.com/sensu-plugins/sensu-plugins-chef/blob/master/sensu-plugins-chef.gemspec#L42

My inference is that perhaps you may be installing this check without using the gem?

**Comment by vegardx** [comment]
There's an issue with 11.18.12 that has been fixed in >= 12.1.0. It's not critical, but it gives you a warning. Making this module compatible with >= 12.7 would fix them both, and get this plugin more in line with Chef in general.

The warning you get when using 11.18.12 and Ruby version newer > 2.2:
`/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/chef-11.18.12/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag`

**Comment by majormoses** [comment]
realtes to: #10 would be more than happy to put a pr together to drop chef 11 support...

**Comment by itdevon** [comment]
I'm running into the same issue as z-matth. I was just wondering if this is a bug that is being worked on or has the issue been fixed?

Here is the error:

      Check failed to run: uninitialized constant Chef::REST, ["/etc/sensu/plugins/check-chef-nodes.rb:99:in `chef_api_connection'", "/etc/sensu/plugins/check-chef-nodes.rb:69:in `connection'", "/etc/sensu/plugins/check-chef-nodes.rb:73:in `nodes_last_seen'", "/etc/sensu/plugins/check-chef-nodes.rb:103:in `any_node_stuck?'", "/etc/sensu/plugins/check-chef-nodes.rb:86:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]

**Comment by cwjohnston** [comment]
Looking at this again, I believe we run into this error because Chef::REST is no longer globally required (per https://blog.chef.io/2016/02/12/chef-client-12-7-released/).

Potential short-term fix would be requiring "chef/rest" instead of "chef". Long term we should look at switching to https://github.com/sethvargo/chef-api

**Comment by majormoses** [comment]
@cwjohnston as chef-api is not considered stable (per the readme) so I would not want to invest the time until it reaches 1.0 I still think its time we use newer versions of chef gem and do a major release. Anyone who needs chef 11 can continue to use it with the pinned major version but will not get any continued development.
